### ISSUE TITLE
[Bug]: Template data (--x509-template-data/--ssh-template-data) not validated when updating a provisioner

### ISSUE THREAD

**Issue by Bobobo-bo-Bo-bobo** [smallstep/certificates#1012]
### Steps to Reproduce

While trying to update a provisioner to use a custom x509 template file, the `--x509-template-data`
option was used with invalid JSON data by a copy&paste error:
```
cert@vasquez:~$ step ca provisioner update maus --x509-template-data=leaf_certificate.tpl 
No admin credentials found. You must login to execute admin commands.
✔ Please enter admin name/subject (e.g., name@example.com): superadmin
✔ Provisioner: Admin JWK (JWK) [kid: mj4o6pbvivgPKyK2GGFVRTmoH3fJb6nTOBoTAoshvfU]
Please enter the password to decrypt the provisioner key: 
```

All provisioners are stored in a PostgreSQL database.

### Your Environment

* OS - Debian 11
* `step-ca` Version - Smallstep CA/0.21.0 (linux/amd64)

### Expected Behavior

Validating the template data before inserting it into the database and reject invalid JSON data.

As an alternative, provide a way to remove the invalid data, like for the `--x509-template-file` option by providing an empty string, e.g. `--x509-template-data=""`

### Actual Behavior

`--x509-template-data` and `--ssh-template-data` happily accept invalid JSON data, rendering the complete step-ca instance inoperable because it will panic upon every provisioner access:

```
cert@vasquez:~$ step ca provisioner list
error getting the provisioners: client GET https://pki.internal.ypbind.de:8443/provisioners?limit=100 failed: Get "https://pki.internal.ypbind.de:8443/provisioners?limit=100": dial tcp 10.147.239.1:8443: connect: connection refused
```
Backtrace:

```
2022/08/14 11:36:33 /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:4362: http2: panic serving 10.147.239.1:57278: json: error calling MarshalJSON for type json.RawMessage: invalid character '{' looking for beginning of object key string
goroutine 429 [running]:
net/http.(*http2serverConn).runHandler.func1()
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:5896 +0x125
panic({0x1359d40, 0xc00084f440})
        /opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x207
github.com/smallstep/certificates/api/render.JSONStatus({0x7fca34278788, 0xc000860660}, {0x1297800, 0xc00084f3e0}, 0xc000042a20?)
        /home/runner/work/certificates/certificates/api/render/render.go:28 +0x15a
github.com/smallstep/certificates/api/render.JSON(...)
        /home/runner/work/certificates/certificates/api/render/render.go:17
github.com/smallstep/certificates/api.Provisioners({0x7fca34278788, 0xc000860660}, 0xc000807900)
        /home/runner/work/certificates/certificates/api/api.go:345 +0x151
net/http.HandlerFunc.ServeHTTP(0x13402e0?, {0x7fca34278788?, 0xc000860660?}, 0xc000042a20?)
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2084 +0x2f
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0006720c0, {0x7fca34278788, 0xc000860660}, 0xc000807900)
        /home/runner/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:425 +0x1f9
net/http.HandlerFunc.ServeHTTP(0x17d5ce8?, {0x7fca34278788?, 0xc000860660?}, 0x20f5430?)
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2084 +0x2f
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0006720c0, {0x7fca34278788, 0xc000860660}, 0xc000807800)
        /home/runner/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:82 +0x3c2
github.com/smallstep/certificates/logging.(*LoggerHandler).ServeHTTP(0xc000012300, {0x17d4ac8, 0xc00000e088}, 0x17c3580?)
        /home/runner/work/certificates/certificates/logging/handler.go:49 +0xa3
github.com/smallstep/certificates/logging.RequestID.func1.1({0x17d4ac8, 0xc00000e088}, 0xc000807700)
        /home/runner/work/certificates/certificates/logging/context.go:38 +0x3d8
net/http.HandlerFunc.ServeHTTP(0xc000042a2e?, {0x17d4ac8?, 0xc00000e088?}, 0xc0000a21e8?)
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0x62ce80?}, {0x17d4ac8, 0xc00000e088}, 0xc000807700)
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2916 +0x43b
net/http.initALPNRequest.ServeHTTP({{0x17d5ce8?, 0xc00084ec60?}, 0xc0000a2000?, {0xc0002c29a0?}}, {0x17d4ac8, 0xc00000e088}, 0xc000807700)
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:3523 +0x245
net/http.(*http2serverConn).runHandler(0x17d1f78?, 0x21524a8?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:5903 +0x78
created by net/http.(*http2serverConn).processHeaders
        /opt/hostedtoolcache/go/1.18.3/x64/src/net/http/h2_bundle.go:5633 +0x59b

```

### Additional Context

Current workaround is to restore the database from backup / previous snapshot.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Bobobo-bo-Bo-bobo** [comment]
Note: I'm not sure if the validation should be done in the client or in the step-ca process or both.

**Comment by hslatman** [comment]
Hey @Bobobo-bo-Bo-bobo,

Sounds like a good thing to add validation for before doing anything with the template. I remember having done something similar with a template loaded from file and/or JSON, but this is an alternate code path that didn't exist at the time. The validation should happen on the CA side for sure. Also performing the validation on the CLI is an option, but would need the logic to be implemented twice, unless it can be reused.

**Comment by Bobobo-bo-Bo-bobo** [comment]
I thing Adding the validation in the server should be enough because the client will receive an error from the service if invalid template data is found and report it back to the user. No need for code duplication.
