### ISSUE TITLE
Incorrect parsing of cache age/jitter in keystore

### ISSUE THREAD

**Issue by matteo-s** [smallstep/certificates#81]
When initializing a keystore with JWKs, keystore.go tries to fetch `age` from `Cache-Control` header.
Unfortunately, when the server responds with something like 
```
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
```
the value extracted from *getCacheAge(cacheControl string)*  is equals to 0 (zero).
Subsequently, `jitter` is set to 0.
This causes an error in subsequent functions, which expect a positive integer as value (see https://golang.org/pkg/math/rand/#Rand.Int63n): 
```
n := rand.Int63n(int64(ks.jitter))

```

A simple fix could be setting a lower bound for jitter in `getCacheJitter` (for example defaultCacheJitter/12).
 

Stacktrace
```
panic: invalid argument to Int63n

goroutine 1 [running]:
math/rand.(*Rand).Int63n(0xc000092150, 0x0, 0xc00019de30)
	/snap/go/3947/src/math/rand/rand.go:111 +0x11e
math/rand.Int63n(...)
	/snap/go/3947/src/math/rand/rand.go:319
github.com/smallstep/certificates/authority/provisioner.(*keyStore).nextReloadDuration(0xc00019de30, 0x0, 0xed4a2c25b)
	/home/mat/go/src/github.com/smallstep/certificates/authority/provisioner/keystore.go:88 +0x3c
github.com/smallstep/certificates/authority/provisioner.newKeyStore(0xc000230100, 0x1d, 0xc000230100, 0x1d, 0x0)
	/home/mat/go/src/github.com/smallstep/certificates/authority/provisioner/keystore.go:46 +0x20f
github.com/smallstep/certificates/authority/provisioner.(*OIDC).Init(0xc0001c8240, 0xc0002222a0, 0xc0002222a8, 0xc0002222b0, 0xc00022229d, 0xc00016da10, 0x3, 0x3, 0xc00016da40, 0x3, ...)
	/home/mat/go/src/github.com/smallstep/certificates/authority/provisioner/oidc.go:146 +0x28e
github.com/smallstep/certificates/authority.(*AuthConfig).Validate(0xc00016d830, 0xc00016da10, 0x3, 0x3, 0xc00016da40, 0x3, 0x3, 0x0, 0xc0001273f8)
	/home/mat/go/src/github.com/smallstep/certificates/authority/config.go:84 +0x275
github.com/smallstep/certificates/authority.(*Config).Validate(0xc000194d00, 0x1b, 0xc00016aa48)
	/home/mat/go/src/github.com/smallstep/certificates/authority/config.go:167 +0x302
github.com/smallstep/certificates/authority.New(0xc000194d00, 0x0, 0x0, 0x0, 0x30, 0x28, 0xad4240)
	/home/mat/go/src/github.com/smallstep/certificates/authority/authority.go:45 +0x40
github.com/smallstep/certificates/ca.(*CA).Init(0xc00016d9e0, 0xc000194d00, 0x2, 0x2, 0x9c6a3d)
	/home/mat/go/src/github.com/smallstep/certificates/ca/ca.go:89 +0x8b
github.com/smallstep/certificates/ca.New(0xc000194d00, 0xc0001276b8, 0x2, 0x2, 0x0, 0xb29eed, 0x4)
	/home/mat/go/src/github.com/smallstep/certificates/ca/ca.go:75 +0xaf
main.startAction(0xc0001d8b00, 0xc000190300, 0xc0001d8b00)
	/home/mat/go/src/github.com/smallstep/certificates/cmd/step-ca/main.go:190 +0x1e4
github.com/smallstep/certificates/vendor/github.com/urfave/cli.HandleAction(0xa43e60, 0xb5e230, 0xc0001d8b00, 0x0, 0xc00016a9c0)
	/home/mat/go/src/github.com/smallstep/certificates/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/smallstep/certificates/vendor/github.com/urfave/cli.Command.Run(0xb2acbf, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/mat/go/src/github.com/smallstep/certificates/vendor/github.com/urfave/cli/command.go:165 +0x487
main.main.func4(0xc0001d8840, 0x0, 0x0)
	/home/mat/go/src/github.com/smallstep/certificates/cmd/step-ca/main.go:152 +0x1ae
github.com/smallstep/certificates/vendor/github.com/urfave/cli.HandleAction(0xa43e60, 0xc00016efc0, 0xc0001d8840, 0x0, 0x0)
	/home/mat/go/src/github.com/smallstep/certificates/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/smallstep/certificates/vendor/github.com/urfave/cli.(*App).Run(0xc000214000, 0xc00000c080, 0x2, 0x2, 0x0, 0x0)
	/home/mat/go/src/github.com/smallstep/certificates/vendor/github.com/urfave/cli/app.go:268 +0x5aa
main.main()
	/home/mat/go/src/github.com/smallstep/certificates/cmd/step-ca/main.go:155 +0x640
```

**Comment by maraino** [comment]
@matteo-s: Thanks for reporting, I'd look into it

**Comment by maraino** [comment]
@matteo-s I've merged my PR to master and created builds for it with the tag `v0.11.0-rc.2`
https://github.com/smallstep/certificates/releases/tag/v0.11.0-rc.2

Let us know if this fix your issues.

**Comment by matteo-s** [comment]
@maraino I've tested against a couple of servers and everything looks ok.
Thanks for the quick fix.
